yaml# .github/workflows/frog.yml
name: Generate Frog Animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate the frog animation using a custom fork of the snake game
      - name: Generate Frog SVG
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-frog.svg
            dist/github-contribution-grid-frog-dark.svg?palette=github-dark
          frog_color: '#00FF00'  # Bright green frog
          hop_height: 4          # Make frog hop higher
          hop_frequency: 0.7     # Control hop frequency
          
      # Push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: Push Frog SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
