name: Generate Frog Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Frog SVG
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: prabhat4002  # ✅ your GitHub username directly here
          outputs: |
            dist/github-contribution-grid-frog.svg
            dist/github-contribution-grid-frog-dark.svg?palette=github-dark

      - name: Push Frog SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
